repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-ast
  - id: check-json
  - id: check-merge-conflict
  - id: requirements-txt-fixer
  - id: name-tests-test
    args: ['--pytest-test-first']
  - id: check-ast
  - id: check-case-conflict
- repo: https://github.com/ambv/black
  rev: 24.4.2
  hooks:
  - id: black
