name: Doc Upload

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  publish-docs:
    runs-on: ubuntu-latest

    steps:
      - uses: ./.github/workflows/python.yml
        with:
          docs: true
