name: python
on:
  workflow_call:
    inputs:
      docs:
        description: Enables/disables docs generation with sphinx
        required: false
        type: boolean
        default: false
      tests:
        description: Toggles running tests
        required: false
        type: boolean
        default: false
jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.7
        if: inputs.tests
      - uses: piotrpawlaczek/python-blacken@v24.4.2
        if: inputs.tests
        with:
          line-length: '128'
#  install:
#    strategy:
#      matrix:
#        python-version: [ "3.8.10", "3.9", "3.10", "3.11", "3.12" ]
#        include:
#          - python-version: "3.12"
#            upload: true
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v4.1.7
#      - uses: actions/setup-python@v5.1.0
#        with:
#          python-version: ${{ matrix.python-version }}
#      - run: python -m pip install build twine --user
#      - run: python -m build --sdist --wheel --outdir dist/
#      - run: twine check dist/*
#      - run: python3 -m pip install .
#      - uses: actions/upload-artifact@v4.3.3
#        if: matrix.upload
#        with:
#          name: build
#          path: dist/*
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.7
        if: inputs.docs
      - uses: actions/setup-python@v5.1.0
        with:
          python-version: "3.12"
        if: inputs.docs
      - run: |
          python -m venv venv
          source ./venv/bin/activate
          make build-docs
          tar -zcf github-pages.tar.gz ./docs/_build/*
        if: inputs.docs
      - uses: actions/upload-artifact@v4.3.3
        if: inputs.docs
        with:
          name: github-pages
          path: github-pages.tar.gz
  pytest:
    strategy:
      matrix:
        python-version: [ "3.8", "3.9", "3.10", "3.11", "3.12" ]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4.1.7
        if: inputs.tests
      - uses: actions/setup-python@v5.1.0
        if: inputs.tests
        with:
          python-version: ${{ matrix.python-version }}
      - name: upgrade pip
        if: inputs.tests
        run: |
          python -m pip install --upgrade pip
      - name: run pip
        if: inputs.tests
        run: |
          pip install -r requirements-dev.txt
      - name: run pytest --cov
        if: inputs.tests
        run: |
          pytest --cov=./ --cov-report=html
      - uses: actions/upload-artifact@v4.3.3
        if: inputs.tests
        with:
          name: coverage_${{ matrix.python-version }}
          if-no-files-found: error
          path: htmlcov
          overwrite: true
